services:
  mysql:
    image: 'mysql:latest'
    container_name: 'MS-reservas_bd'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-bd_reservas}
      MYSQL_USER: ${DB_USER:-user_dev}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dev_password}

    ports:
      - '3314:3306'

    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: MS_Reservas_Gui
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - '9014:80'

      #Actualmente estamos en entorno local, se desabilitaran estos parametros
      #- 'MYSQL_USER=admin'
      #- 'MYSQL_PASSWORD=root'
      