# Nombre del microservicio
spring.application.name=Canchas
server.port=8083

# Configuración de Base de Datos (MySQL - Corregido al puerto 3308 de tu contenedor)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/bd_canchas}
spring.datasource.username=${DB_USER:user_dev}
spring.datasource.password=${DB_PASSWORD:dev_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# Migraciones (Desactivadas)
spring.flyway.enabled=false

# Ejecutar datos iniciales usando SQL estándar
spring.sql.init.mode=always

# Configuración de Seguridad JWT
jwt.secret=ClaveUltraSecretaEInviolableParaLaMunicipalidad2026!
jwt.issuer=ms-auth

# ===================================================================
# PREVENCIÓN DE BLOQUEOS EN DOCKER (Evita el congelamiento en consola)
# ===================================================================
spring.docker.compose.enabled=false

# ===================================================================
# CONFIGURACIÓN DE SWAGGER / SPRINGDOC (Sincronizada con el Gateway y Controller)
# ===================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# 🛠️ CORREGIDO: Mueve el JSON de OpenAPI al prefijo correcto de la app
springdoc.api-docs.path=/api/v1/canchas/v3/api-docs